# Development Environment Configuration
# This configuration is used for local development

environment: development
debug: true

# Large Language Model Configuration
llm:
  primary_provider: "openai"
  fallback_provider: "anthropic"
  use_fallback: true
  providers:
    openai:
      name: "openai"
      model: "gpt-4"
      base_url: null  # Uses default OpenAI API
      max_tokens: 2048
      temperature: 0.7
      timeout: 60
      max_retries: 3
      retry_delay: 1.0
    anthropic:
      name: "anthropic"
      model: "claude-3-sonnet-20240229"
      base_url: "https://api.anthropic.com"
      max_tokens: 2048
      temperature: 0.7
      timeout: 60
      max_retries: 3
      retry_delay: 1.0
    ollama:
      name: "ollama"
      model: "llama2"
      base_url: "http://localhost:11434"
      max_tokens: 2048
      temperature: 0.7
      timeout: 120
      max_retries: 3
      retry_delay: 2.0

# Object Storage Configuration
object_storage:
  provider: "aws"  # aws, minio, r2, wasabi, custom
  endpoint_url: null  # Use default for AWS, set for others
  region: "us-east-1"
  bucket_name: "ai-3d-assets-dev"
  bucket_public: "ai-3d-assets-public-dev"
  custom_domain: null
  use_ssl: true
  presigned_url_expiry: 3600
  max_file_size: 104857600  # 100MB
  allowed_extensions:
    - ".obj"
    - ".gltf"
    - ".fbx"
    - ".glb"
    - ".png"
    - ".jpg"
    - ".jpeg"
    - ".mtl"
  cleanup_after_days: 7
  multipart_threshold: 67108864  # 64MB
  max_concurrency: 5

# 3D Generation Configuration
threed_generation:
  primary_service: "meshy"
  fallback_service: "kaedim"
  generation_timeout: 300
  polling_interval: 10
  max_polling_attempts: 60
  quality_preset: "standard"
  output_formats:
    - "obj"
    - "gltf"
  texture_resolution: 1024

# Gradio Web Interface Configuration
gradio:
  host: "127.0.0.1"
  port: 7860
  debug: true
  share: false
  max_file_size: 52428800  # 50MB
  queue_max_size: 10
  show_error: true
  theme: "default"
  title: "AI 3D Asset Generator - Development"
  description: "Generate 3D assets from text descriptions (Development Mode)"

# Database Configuration (SQLite for development)
database:
  url: "sqlite:///./data/assets_dev.db"
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600
  echo: true

# Logging Configuration
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
  file_path: "./logs/app_dev.log"
  max_file_size: 10485760  # 10MB
  backup_count: 3
  json_format: false

# Security Configuration
security:
  secret_key: "development-secret-key-change-in-production-must-be-32-chars-long"
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"
    - "0.0.0.0"
  cors_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://localhost:7860"
  max_request_size: 104857600  # 100MB
  rate_limit_requests: 1000
  rate_limit_window: 60
  api_key_header: "X-API-Key"

# Application Settings
app_name: "AI 3D Asset Generator"
app_version: "0.1.0"
asset_cache_ttl: 1800  # 30 minutes for development
temp_dir: "./temp/ai-3d-assets"
max_concurrent_generations: 3
