# Docker Environment Configuration
# This configuration is optimized for Docker container deployment

environment: production
debug: false

# Large Language Model Configuration
llm:
  provider: "openai"
  providers:
    openai:
      model: "gpt-4"
      base_url: null
      max_tokens: 2048
      temperature: 0.7
      timeout: 120
      max_retries: 3
      retry_delay: 1.5
    anthropic:
      name: "anthropic"
      model: "claude-3-sonnet-20240229"
      base_url: "https://api.anthropic.com"
      max_tokens: 2048
      temperature: 0.7
      timeout: 120
      max_retries: 3
      retry_delay: 1.5

# Object Storage Configuration
object_storage:
  endpoint_url: null
  region: "us-east-1"
  bucket_name: "ai-3d-assets-docker"
  use_ssl: true
  max_file_size: 209715200  # 200MB

# 3D Generation Configuration
threed_generation:
  service: "meshy"
  generation_timeout: 600  # 10 minutes
  polling_interval: 10
  max_polling_attempts: 120
  quality_preset: "standard"
  output_formats:
    - "obj"
    - "gltf"
  texture_resolution: 1024

# Gradio Web Interface Configuration
gradio:
  host: "0.0.0.0"
  port: 7860
  debug: false
  share: false
  max_file_size: 104857600  # 100MB
  queue_max_size: 20
  show_error: false
  theme: "default"
  title: "AI 3D Asset Generator"
  description: "Generate 3D assets from text descriptions"

# Database Configuration (PostgreSQL in Docker)
database:
  url: "postgresql://postgres:postgres@postgres:5432/ai_3d_assets"
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600
  echo: false

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: null  # Log to stdout in Docker
  max_file_size: 52428800  # 50MB
  backup_count: 3
  json_format: true

# Security Configuration
security:
  # This will be set via environment variable
  secret_key: "docker-default-secret-key-override-with-env-var-32-chars"
  allowed_hosts:
    - "*"  # Allow all hosts in Docker (configure reverse proxy appropriately)
  cors_origins:
    - "*"  # Allow all origins in Docker (configure reverse proxy appropriately)
  max_request_size: 209715200  # 200MB
  rate_limit_requests: 100
  rate_limit_window: 60
  api_key_header: "X-API-Key"

# Application Settings
app_name: "AI 3D Asset Generator"
app_version: "0.1.0"
asset_cache_ttl: 3600  # 1 hour
temp_dir: "/app/temp"
max_concurrent_generations: 5

# Docker-specific settings
docker:
  container_name: "ai-3d-asset-generator"
  restart_policy: "unless-stopped"
  memory_limit: "2g"
  cpu_limit: "1.0"
  
# Health check configuration
health_check:
  enabled: true
  endpoint: "/health"
  interval: 30
  timeout: 10
  retries: 3

# Volume mounts
volumes:
  temp_data: "/app/temp"
  logs: "/app/logs"
  models_cache: "/app/cache"
