# Production Environment Configuration
# This configuration is used for production deployment

environment: production
debug: false

# Large Language Model Configuration
llm:
  provider: "openai"
  providers:
    openai:
      model: "gpt-4"
      base_url: null
      max_tokens: 2048
      temperature: 0.7
      timeout: 90
      max_retries: 5
      retry_delay: 2.0
    anthropic:
      name: "anthropic"
      model: "claude-3-sonnet-20240229"
      base_url: "https://api.anthropic.com"
      max_tokens: 2048
      temperature: 0.7
      timeout: 90
      max_retries: 5
      retry_delay: 2.0

# Object Storage Configuration
object_storage:
  endpoint_url: null
  region: "us-east-1"
  bucket_name: "ai-3d-assets-prod"
  use_ssl: true
  max_file_size: 209715200  # 200MB

# 3D Generation Configuration
threed_generation:
  service: "meshy"
  generation_timeout: 600  # 10 minutes
  polling_interval: 15
  max_polling_attempts: 120
  quality_preset: "high"
  output_formats:
    - "obj"
    - "gltf"
    - "fbx"
  texture_resolution: 2048

# Gradio Web Interface Configuration
gradio:
  host: "0.0.0.0"
  port: 7860
  debug: false
  share: false
  max_file_size: 104857600  # 100MB
  queue_max_size: 50
  show_error: false
  theme: "default"
  title: "AI 3D Asset Generator"
  description: "Transform text descriptions into professional 3D game assets"

# Database Configuration (PostgreSQL for production)
database:
  url: "postgresql://user:password@db:5432/ai_3d_assets"
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600
  echo: false

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "/var/log/ai-3d-assets/app.log"
  max_file_size: 52428800  # 50MB
  backup_count: 5
  json_format: true

# Security Configuration
security:
  # This should be set via environment variable SECURITY__SECRET_KEY
  secret_key: "CHANGE_ME_IN_PRODUCTION_MINIMUM_32_CHARACTERS_REQUIRED"
  allowed_hosts:
    - "ai-3d-assets.example.com"
    - "api.ai-3d-assets.example.com"
  cors_origins:
    - "https://ai-3d-assets.example.com"
    - "https://app.ai-3d-assets.example.com"
  max_request_size: 209715200  # 200MB
  rate_limit_requests: 100
  rate_limit_window: 60
  api_key_header: "X-API-Key"

# Application Settings
app_name: "AI 3D Asset Generator"
app_version: "0.1.0"
asset_cache_ttl: 3600  # 1 hour
temp_dir: "/tmp/ai-3d-assets"
max_concurrent_generations: 10

# Production-specific settings
monitoring:
  enabled: true
  metrics_port: 8080
  health_check_port: 8081

backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
